
/* **********************************************************************
   * Boarding.H - Universal Mayhem, Version 2.7, Copyright Fredric L.   *
   * Rice, 1991. All rights reserved.                                   *
   *                                                                    *
   ********************************************************************** */

void boarding_party(char ship_or_base, short which);

       
