
/* **********************************************************************
   * Landing.H - Universal Mayhem, Version 2.7, Copyright Fredric L.    *
   * Rice, 1991. All rights reserved.                                   *
   *                                                                    *
   ********************************************************************** */

void landing_party(void);

