c:\tcpp\lib\c0l+ship+input+warp+close+fileio+random+color+async+command+distrib+sled+rpt+scout+ /o base+board+comets+buysell+destruct+extend+findgo+help+info+leave+long+mail+name+names+peace+plague+power+protect+stand+stat+sysop+taxes+time+free+ping+auction+leash+maydrop+support1+quit+remote+spy+torp+scan+nav+cops+goals+phaser+landing+boarding
ship.exe
ship.map
c:\tcpp\lib\overlay.lib+c:\tcpp\lib\emu.lib+c:\tcpp\lib\mathl.lib+c:\tcpp\lib\cl.lib+c:\tcpp\lib\fp87.lib

